// <auto-generated />
namespace DataBaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Entidad_Moneda_Relacion_Entrada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Entidad_Moneda_Relacion_Entrada));
        
        string IMigrationMetadata.Id
        {
            get { return "201908090200385_Entidad_Moneda_Relacion_Entrada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
