// <auto-generated />
namespace DataBaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CamposUnicosArea_Nombre_Usuario_NombreUsuario_Correo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CamposUnicosArea_Nombre_Usuario_NombreUsuario_Correo));
        
        string IMigrationMetadata.Id
        {
            get { return "201906210115021_CamposUnicosArea_Nombre_Usuario_NombreUsuario_Correo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
